Books/Components/CartSummaryViewComponent.cs
using Books.Models;
using Microsoft.AspNetCore.Mvc;
namespace SportsStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket cart;
        public CartSummaryViewComponent(Basket cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Books/Components/CartViewComponent.cs
using Books.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Books.Components
{
    public class CartViewComponent : ViewComponent
    {
        private Basket basket;
        public CartViewComponent(Basket b)
        {
            basket = b;
        }
        public IViewComponentResult Invoke()
        {
            return View(basket);
        }
    }
}

Books/Components/CategoryViewComponent.cs
using Books.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Books.Components
{
    public class CategoryViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public CategoryViewComponent(IBookstoreRepository b)
        {
            repo = b;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.Category = RouteData?.Values["category"];

            var types = repo.BookRepo
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return View(types);
        }
    }
}

Books/Views/Shared/BookSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Book

<div class="card card-outline-warning m-1 p-1">

    <div class="bg-light p-1">
        <h3>@Model.Title</h3>
        <span class="badge rounded-pill bg-info" style="float:left">
            @Model.Author
        </span>
    </div>

    <ul>
        <li>Publisher: @Model.Publisher</li>
        <li>ISBN: @Model.Isbn</li>
        <li>Classification: @Model.Classification</li>
        <li>Category: @Model.Category</li>
        <li>Page count: @Model.PageCount</li>
        <li>Price: @Model.Price</li>
    </ul>

    <form method="post" asp-page="/Cart">
        <input type="hidden" asp-for="@Model.BookId"/>
        <input type="hidden" name="return_url" value="@ViewContext.HttpContext.Request.PathAndQuery()"
        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Add To Cart</button>
        </span>
    </form>
</div>

Books/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Books</title>
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>

    <nav class="navbar navbar-dark text-white bg-dark p-2">
        <a class="navbar-brand">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" overflow="0" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
                <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z" />
            </svg>
            AMAZON BOOKS
            <vc:cart-summary />
        </a>
    </nav>

    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:category></vc:category>
        </div>
        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>