Books/Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Books.Infastructure;
using Books.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Books.Pages
{
    public class CartModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }

        public CartModel(IBookstoreRepository r, Basket b)
        {
            repo = r;
            Basket = b;
        }

        public Basket Basket { get; set; }
        public string ReturnUrl { get; set; } //Make it persist.

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            /*            Basket = HttpContext.Session.GetJson<Basket>("basket") ?? new Basket();*/
        }
        public IActionResult OnPost(int bookId, string returnUrl)
        {
            //?? Null Coalesing Operator. If the first isnt null use that, else use the thing on the right.
            var book = repo.BookRepo.FirstOrDefault(x => x.BookId == bookId);
            /*            Basket = HttpContext.Session.GetJson<Basket>("basket") ?? new Basket();*/
            Basket.AddItem(book, 1);

            /*            HttpContext.Session.SetJson("basket", Basket);*/

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            Basket.RemoveItem(Basket.Items.First(x => x.Book.BookId == bookId).Book);
            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

Books/Pages/CheckoutCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Books.Pages
{
    public class CheckoutCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Books/Pages/Cart.cshtml
@page
@model Books.Pages.CartModel
@{
}

<h2>Your Cart:</h2>

<table class="table table-bordered table-striped">
    <thread>
        <tr>
            <th>Item</th>
            <th>Quantiy</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thread>

    <tbody>
        @foreach (var x in Model.Basket.Items)
        {
            <tr>
                <td>@x.Book.Title</td>
                <td>@x.Quantity</td>
                <td>@(x.Book.Price.ToString("c"))</td>
                <td>@((x.Quantity * x.Book.Price).ToString("c"))</td>

                <td class="text-center">
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="bookId" value="@x.Book.BookId"/>
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total: </td>
            <td>@Model.Basket.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>
<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Buy">Checkout</a>
</div>

Books/Pages/CheckoutCompleted.cshtml
@page
@model Books.Pages.CheckoutCompletedModel
@{
}

<div class="jumbotron jumbotron-fluid">
    <div class="container text-center">
        <h2><span class="display-4">Thank you for your buisness!</span></h2>
        <a class="btn btn-primary" asp-controller="Home">Return Home</a>
    </div>
</div>

Books/Pages/_CartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

    <nav class="navbar navbar-dark text-white bg-dark p-2">
        <a class="navbar-brand">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" overflow="0" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
                <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z" />
            </svg>
            AMAZON BOOKS
        </a>
    </nav>
    <div class="row m-1 p-1">
        <div>
            @RenderBody()
        </div>
    </div>
</body>
</html>